<a href="https://colab.research.google.com/github/Shiva-15711/AI/blob/main/Random_forest_wine_prediction_Team_19(19K41A05B1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mount Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Import Libraries

In [2]:
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd

Load Data

In [3]:
data = pd.read_csv("/content/drive/MyDrive/AI_data/Winequality_dataset_final.csv")
data.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        0
1            7.8              0.88         0.00  ...       0.68      9.8        0
2            7.8              0.76         0.04  ...       0.65      9.8        0
3           11.2              0.28         0.56  ...       0.58      9.8        1
4            7.4              0.70         0.00  ...       0.56      9.4        0

[5 rows x 11 columns]

# Min max values

In [4]:
fixed_min = data['fixed acidity'].min()
fixed_max = data['fixed acidity'].max()
volatile_min = data['volatile acidity'].min()
volatile_max = data['volatile acidity'].max()
citric_min = data['citric acid'].min()
citric_max = data['citric acid'].max()
residual_min = data['residual sugar'].min()
residual_max = data['residual sugar'].max()
chlorides_min = data['chlorides'].min()
chlorides_max = data['chlorides'].max()
free_min = data['free sulfur dioxide'].min()
free_max = data['free sulfur dioxide'].max()
total_min = data['total sulfur dioxide'].min()
total_max = data['total sulfur dioxide'].max()
density_min = data['density'].min()
density_max = data['density'].max()
sulphates_min = data['sulphates'].min()
sulphates_max = data['sulphates'].max()
alcohol_min = data['alcohol'].min()
alcohol_max = data['alcohol'].max()
quality_min = data['quality'].min()
quality_max = data['quality'].max()

print(fixed_min, fixed_max, volatile_min, volatile_max, citric_min, citric_max, residual_min, residual_max, chlorides_min, chlorides_max, free_min, free_max,total_min, total_max,density_min, density_max,sulphates_min, sulphates_max,alcohol_min, alcohol_max,quality_min, quality_max)

4.6 15.9 0.12 1.58 0.0 1.0 0.9 15.5 0.012 0.611 1.0 72.0 6.0 289.0 0.9900700000000001 1.00369 0.33 2.0 8.4 14.9 0 1


# Normalization

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
# Applying scaler() to all the columns except the 'yes-no' and 'dummy' variables
num_vars = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide',
            'total sulfur dioxide', 'density', 'sulphates', 'alcohol', 'quality']
data[num_vars] = scaler.fit_transform(data[num_vars])

data.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates   alcohol  quality
0       0.247788          0.397260         0.00  ...   0.137725  0.153846      0.0
1       0.283186          0.520548         0.00  ...   0.209581  0.215385      0.0
2       0.283186          0.438356         0.04  ...   0.191617  0.215385      0.0
3       0.584071          0.109589         0.56  ...   0.149701  0.215385      1.0
4       0.247788          0.397260         0.00  ...   0.137725  0.153846      0.0

[5 rows x 11 columns]

Data Split

In [6]:
#split dataset in features and target variable
feature_cols = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density','sulphates','alcohol']
X = data[feature_cols] 
y = data.quality

In [7]:
# Split dataset into training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

Random Forest Model Training

In [8]:
#Fitting Decision Tree classifier to the training set  
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(criterion="entropy")  
classifier.fit(X_train, y_train)  

RandomForestClassifier(criterion='entropy')

In [9]:
# Predicting the training and testing results
y_pred_test= classifier.predict(X_test)  
y_pred_train= classifier.predict(X_train) 

In [10]:
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
print("Accuracy for training Data",metrics.accuracy_score(y_train, y_pred_train))
print("Accuracy for testing Data",metrics.accuracy_score(y_test, y_pred_test))

Accuracy for training Data 1.0
Accuracy for testing Data 0.8145833333333333


In [11]:
#Fitting Decision Tree classifier to the training set  
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(criterion="gini")  
classifier.fit(X_train, y_train)  

RandomForestClassifier()

In [12]:
# Predicting the training and testing results
y_pred_test= classifier.predict(X_test)  
y_pred_train= classifier.predict(X_train) 

In [13]:
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
print("Accuracy for training Data",metrics.accuracy_score(y_train, y_pred_train))
print("Accuracy for testing Data",metrics.accuracy_score(y_test, y_pred_test))

Accuracy for training Data 1.0
Accuracy for testing Data 0.81875


In [14]:
#Fitting Decision Tree classifier to the training set  
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 4, criterion="entropy")  
classifier.fit(X_train, y_train)  

RandomForestClassifier(criterion='entropy', n_estimators=4)

Prediction

In [15]:
# Predicting the training and testing results
y_pred_test= classifier.predict(X_test)  
y_pred_train= classifier.predict(X_train) 

Model Metrics

In [16]:
# Confusion matrix for testing Data  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_train, y_pred_train)
cm  

array([[504,  10],
       [ 54, 551]])

In [17]:
# Confusion matrix for testing Data  
from sklearn.metrics import confusion_matrix  
cm1= confusion_matrix(y_test, y_pred_test)
cm1  

array([[191,  39],
       [ 80, 170]])

In [18]:
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
print("Accuracy for training Data",metrics.accuracy_score(y_train, y_pred_train))
print("Accuracy for testing Data",metrics.accuracy_score(y_test, y_pred_test))

Accuracy for training Data 0.9428060768543343
Accuracy for testing Data 0.7520833333333333


Model Training gini index

In [19]:
#Fitting Decision Tree classifier to the training set  
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 4, criterion="gini")  
classifier.fit(X_train, y_train)  

RandomForestClassifier(n_estimators=4)

Model Prediction

In [20]:
# Predicting the training and testing results
y_pred_test= classifier.predict(X_test)  
y_pred_train= classifier.predict(X_train) 

In [21]:
# Confusion matrix for testing Data  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_train, y_pred_train)
cm  

array([[504,  10],
       [ 45, 560]])

In [22]:
# Confusion matrix for testing Data  
from sklearn.metrics import confusion_matrix  
cm1= confusion_matrix(y_test, y_pred_test)
cm1  

array([[198,  32],
       [ 89, 161]])

In [23]:
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
print("Accuracy for training Data gini index ",metrics.accuracy_score(y_train, y_pred_train))
print("Accuracy for testing Data gini index ",metrics.accuracy_score(y_test, y_pred_test))

Accuracy for training Data gini index  0.9508489722966935
Accuracy for testing Data gini index  0.7479166666666667


Save the Model

In [24]:
import pickle
# Save the model
filename = 'random_forest_model.pkl'
pickle.dump(classifier, open(filename, 'wb'))

Deployment

In [25]:
list_of_columns = data.columns
input_data=pd.DataFrame(columns=list_of_columns)
input_data.drop(['quality'], axis='columns', inplace=True)


input_data.at[0, 'fixed acidity'] = float(input('Enter Fixed Acidity Content '))
input_data.at[0, 'volatile acidity'] = float(input('Enter Volatile Acidity Content '))
input_data.at[0, 'citric acid'] = float(input('Enter Citric Acid Content '))
input_data.at[0, 'residual sugar'] = float(input('Enter residual Sugar Content '))
input_data.at[0, 'chlorides'] = float(input('Enter Chlorides Content '))
input_data.at[0, 'free sulfur dioxide'] = float(input('Enter Free Sulphur Dioxide Content '))
input_data.at[0, 'total sulfur dioxide'] = float(input('Enter total Sulphur Dioxide Content'))
input_data.at[0, 'density'] = float(input('Enter Density Content'))
input_data.at[0, 'sulphates'] = float(input('Enter Sulphates Content'))
input_data.at[0, 'alcohol'] = float(input('Enter Alcohol Content'))

Enter Fixed Acidity Content 7.4
Enter Volatile Acidity Content 0.7
Enter Citric Acid Content 0
Enter residual Sugar Content 1.9
Enter Chlorides Content .076
Enter Free Sulphur Dioxide Content 11
Enter total Sulphur Dioxide Content34
Enter Density Content0.9978
Enter Sulphates Content0.56
Enter Alcohol Content9.4


Denormalization

In [26]:
input_data['fixed acidity']=(input_data['fixed acidity']-fixed_min)/(fixed_max-fixed_min)
input_data['volatile acidity']=(input_data['volatile acidity']-volatile_min)/(volatile_max-volatile_min)
input_data['citric acid']=(input_data['citric acid']-citric_min)/(citric_max-citric_min)
input_data['residual sugar']=(input_data['residual sugar']-residual_min)/(residual_max-residual_min)
input_data['chlorides']=(input_data['chlorides']-chlorides_min)/(chlorides_max-chlorides_min)
input_data['free sulfur dioxide']=(input_data['free sulfur dioxide']-free_min)/(free_max-free_min)
input_data['total sulfur dioxide']=(input_data['total sulfur dioxide']-total_min)/(total_max-total_min)
input_data['density']=(input_data['density']-density_min)/(density_max-density_min)
input_data['sulphates']=(input_data['sulphates']-sulphates_min)/(sulphates_max-sulphates_min)
input_data['alcohol']=(input_data['alcohol']-alcohol_min)/(alcohol_max-alcohol_min)

y_pred =  classifier.predict(input_data)
quality = y_pred*(quality_max-quality_min)+quality_min
if quality == 1:
  print('The wine quality is good.')
else:
  print('The quality of wine is bad.')

The quality of wine is bad.
